# Generated by Django 2.0.2 on 2018-03-27 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_description', models.CharField(max_length=200)),
                ('faculty_id', models.BigIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('my_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='Course.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=50)),
                ('lesson_seqname', models.IntegerField()),
                ('lesson_description', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('my_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='Course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_item_name', models.CharField(max_length=50)),
                ('lesson_item_seqname', models.IntegerField()),
                ('lesson_item_asset_link', models.CharField(blank=True, max_length=200, null=True)),
                ('lesson_item_description', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('my_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
                ('my_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_items', to='Course.Lesson')),
            ],
        ),
    ]
