# Generated by Django 2.0.1 on 2018-02-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_description', models.CharField(max_length=200)),
                ('faculty_id', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('lid', models.BigAutoField(primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(max_length=50)),
                ('lesson_seqname', models.IntegerField()),
                ('lesson_description', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('my_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons_items',
            fields=[
                ('lid', models.BigAutoField(primary_key=True, serialize=False)),
                ('lesson_item_name', models.CharField(max_length=50)),
                ('lesson_item_seqname', models.IntegerField()),
                ('lesson_item_description', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('my_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
                ('my_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Lessons')),
            ],
        ),
    ]
