# Generated by Django 2.0.1 on 2018-02-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lid', models.BigAutoField(primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(max_length=50)),
                ('lesson_seqname', models.IntegerField()),
                ('lesson_description', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons_item',
            fields=[
                ('lid', models.BigAutoField(primary_key=True, serialize=False)),
                ('lesson_item_name', models.CharField(max_length=50)),
                ('lesson_item_seqname', models.IntegerField()),
                ('lesson_item_description', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='my_course',
        ),
        migrations.RemoveField(
            model_name='lessons_items',
            name='my_course',
        ),
        migrations.RemoveField(
            model_name='lessons_items',
            name='my_lesson',
        ),
        migrations.AlterField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Lessons',
        ),
        migrations.DeleteModel(
            name='Lessons_items',
        ),
        migrations.AddField(
            model_name='lessons_item',
            name='my_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course'),
        ),
        migrations.AddField(
            model_name='lessons_item',
            name='my_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='my_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course'),
        ),
    ]
