# Generated by Django 2.0.2 on 2018-03-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_description', models.CharField(max_length=200)),
                ('faculty', models.BigIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lid', models.BigAutoField(primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(max_length=50)),
                ('lesson_seqnum', models.IntegerField(null=True)),
                ('lesson_desc', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Litem',
            fields=[
                ('liid', models.BigAutoField(primary_key=True, serialize=False)),
                ('litem_name', models.CharField(max_length=50)),
                ('litem_seqnum', models.IntegerField(null=True)),
                ('litem_desc', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='litems',
            field=models.ManyToManyField(to='courseapp.Litem'),
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(to='courseapp.Lesson'),
        ),
        migrations.AddField(
            model_name='category',
            name='courses',
            field=models.ManyToManyField(to='courseapp.Course'),
        ),
    ]
