# Generated by Django 2.0.2 on 2018-02-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_auto_20180226_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty_id',
            field=models.BigIntegerField(),
        ),
    ]
