# Generated by Django 2.0.2 on 2018-02-27 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_auto_20180226_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lid', models.BigAutoField(primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(max_length=50)),
                ('lesson_seqnum', models.IntegerField()),
                ('lesson_desc', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.Course')),
            ],
        ),
    ]
