# Generated by Django 2.0.2 on 2018-02-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course_id',
            new_name='course',
        ),
    ]
