# Generated by Django 2.0.2 on 2018-02-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0005_auto_20180227_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course',
            new_name='course_id',
        ),
    ]
