# Generated by Django 2.0.2 on 2018-02-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0006_auto_20180227_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
