# Generated by Django 2.0.2 on 2018-02-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0007_auto_20180227_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseapp.Course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_seqnum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
