# Generated by Django 2.0.2 on 2018-02-27 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0008_auto_20180227_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Litem',
            fields=[
                ('liid', models.BigAutoField(primary_key=True, serialize=False)),
                ('litem_name', models.CharField(max_length=50)),
                ('litem_seqname', models.IntegerField()),
                ('litem_desc', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('lesson_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseapp.Lesson')),
            ],
        ),
    ]
