# Generated by Django 2.0.2 on 2018-03-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0009_litem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='litem',
            old_name='litem_seqname',
            new_name='litem_seqnum',
        ),
    ]
