# Generated by Django 2.0.2 on 2018-03-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0010_auto_20180306_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='faculty_id',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='litem',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
