# Generated by Django 2.0.2 on 2018-03-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0011_auto_20180306_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ManyToManyField(to='courseapp.Course'),
        ),
    ]
