# Generated by Django 2.0.2 on 2018-03-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0012_auto_20180309_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='lesson',
            field=models.ManyToManyField(to='courseapp.Lesson'),
        ),
    ]
