# Generated by Django 2.0.2 on 2018-03-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0012_auto_20180309_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_seqnum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='litem',
            name='litem_seqnum',
            field=models.IntegerField(null=True),
        ),
    ]
