# Generated by Django 2.0.2 on 2018-03-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0013_auto_20180309_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(null=True, to='courseapp.Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='litems',
            field=models.ManyToManyField(null=True, to='courseapp.Litem'),
        ),
    ]
