# Generated by Django 2.0.2 on 2018-03-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0014_auto_20180309_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lesson',
            field=models.ManyToManyField(blank=True, null=True, to='courseapp.Lesson'),
        ),
    ]
