# Generated by Django 2.0.2 on 2018-03-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0016_auto_20180309_2324'),
        ('courseapp', '0015_auto_20180309_1907'),
    ]

    operations = [
    ]
